services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "5000:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      api:
        condition: service_healthy